### PR TITLE
I've created a working snap for whatsthis

### PR DESCRIPTION
**Pull request by kz6fittycent**
The snap needs to get approval for the system-files interface OR classic confinement. 

Let me know if you need anything else from me.

### CODE REVIEW

**Comment by powersj** [comment]
Hey! Thanks for the pull request and doing the work here. I am happy to pull this. It does look like you have the name reserved in the snap store now, so you would need to publish.

**Comment by kz6fittycent** [comment]
Yeah...didn't think that one through! I'm happy to keep it going as I've got the snap pointed to your repo anyway. What are your thoughts about classic confinement for this snap? Is it worth pursuing?

**Comment by powersj** [comment]
When I started thinking about how to deliver this I wanted it to be something easy to install/distribute like the other projects you have seen me work on. A snap fit that model. 

Because this app would introspect the system details I also wondered about using it as a classic snap. To get a classic confined snap published to the stable channel you do have to get permission and provide justification. That is fine, but given I was still outlining how the app worked I wanted to put things together more first, before asking for classic confinement.

All that said, I would be happy leaving it as classic for now and we you or others could install it from the edge channel in the mean time.

**Comment by kz6fittycent** [comment]
> When I started thinking about how to deliver this I wanted it to be something easy to install/distribute like the other projects you have seen me work on. A snap fit that model.
> 
> Because this app would introspect the system details I also wondered about using it as a classic snap. To get a classic confined snap published to the stable channel you do have to get permission and provide justification. That is fine, but given I was still outlining how the app worked I wanted to put things together more first, before asking for classic confinement.
> 
> All that said, I would be happy leaving it as classic for now and we you or others could install it from the edge channel in the mean time.

In that case, I can just wait until I get the word from you to proceed. I like the idea behind it though! It'll be a very nice tool for sysadmins in the future. 

I've moved ownership of snaps in the past, and we can do that again here if you want. At least we know that the current snap "works".

**Comment by powersj** [comment]
I'm going to merge this :) I appreciate the time you put in to get this working. When I get a bit further along we can go through transferring it and fixing up any remaining plugs I might need.

Thank you for the time you put into getting this going.

**Pull request merged**
